name = "backend"
compatibility_date = "2023-12-01"

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiZmNiZDcyNDQtODk3Yy00MWJjLTk0NWQtY2I3NmQ3ZDllY2QxIiwidGVuYW50X2lkIjoiNTY5ZDIwNDgwMmI1MTJhNDIxOGQ4YjQ2NGEwZTE5YjhjODRiM2ZhZTFmZGVjNWNiMGEzMzdlYTllZTFjM2FiOCIsImludGVybmFsX3NlY3JldCI6IjFkYWU3M2MwLTY1ZTQtNGE5ZS1iYTQyLTczMjYzNTExYjU4NyJ9.tbg-D1PKIJZdBvK5vDK2uvLNHyKy72Rv53VrLioNSvk"
JWT_SECRET="secretkey"